### ISSUE TITLE
Make package Fable compiler compatible

### ISSUE THREAD

**Issue by danyx23** [cmeeren/Cvdm.ErrorHandling#7] opened 2018-07-02 07:06 UTC
We are using the SAFE stack and it would be great if we could use this nuget package also on the frontend code that is compiled with Fable. Since fable transpiles to Javascript from F# source code, Nuget packages that are to be used by Fable need to be compiled in a way that [includes the F# source code](http://fable.io/blog/Paket-integration.html#for-library-authors) in the nuget package. Would you be open to a pull request that introduces the paket nuget package manager to this repo and sets up the nuget package to be used with Fable?

**Comment by cmeeren** [comment] 2018-07-02 11:15
I am certainly willing to make this Fable compatible. Could release 1.0.0 at the same time, I consider this package more than stable enough for a "proper" release. A couple of questions, though:

1. Is Paket necessary, or can we make this work with Nuget? (If yes, what are the pros/cons of each approach?)
2. Will using Paket neccesitate CI/CD changes?
3. Are there any (other) drawbacks to using Paket for this repo as opposed to Nuget?

**Comment by danyx23** [comment] 2018-07-04 06:45
Good questions :). I looked into this a bit more and realized that even though the fable docs speak only of paket, all the hard work is actually done by vanilla msbuild. So everything can stay just as it is, the PR would just add instructions to the library .fsproj file to include the fsproj file and fsharp files from the library in the nuget package under the fable folder. I have used the [Nuget package explorer](https://www.microsoft.com/de-de/p/nuget-package-explorer/9wzdncrdmdm3?rtc=1&activetab=pivot%3Aoverviewtab) to make sure that the layout of the resulting nuget package is as it should be without introducing paket. I'll send a PR with just these minor changes that should make the package Fable compatible once I was able to try the whole cycle of consuming a local copy from Fable.

**Comment by danyx23** [comment] 2018-07-04 07:36
I just tried this and initially ran into problems where the Fable compiler could not find the source files to do it's work. I looked into the dependencies of Cvdm.ErrorHandling and suspected that the additional dependencies of System.ValueTuple and NETStandard.Library might trip fable up in the targest other than .NETStanrdard 2.0. Indeed it turned out that if I recreate the nuget package for Cvdm.ErrorHandling with only a target of .NETStandard 2.0, fable is correctly able to find the source code and compile everything. 

This leaves us at a bit of a conundrum. What is your opinion on only targeting .NETStandard 2.0? I can also open an issue with the fable compiler but that might take a while to get resolved. I did try to restrict the compilation of my fable test project to .NETStandard to make sure the other dependencies are not pulled in but that didn't help.

**Comment by cmeeren** [comment] 2018-07-04 09:04
I don't want to force my users to use .NET Standard 2.0 when the package also works great with other targets. But I don't understand why this should be a problem in the first place. If Fable works with the 2.0 version, why can't it just use that? Could you explain the problem in more detail?

**Comment by inosik** [comment] 2018-07-04 09:52
@danyx23 Can you forward that to Fable, please? It looks like Fable has a problem with the `AutoOpen` attribute. Adding `open Cvdm.ErrorHandling` to my test file makes it work.

@cmeeren For you as the package author, it should be enough to add these lines to the librarys project file:

``` xml
  <ItemGroup>
    <Content Include="*.fsproj; *.fs" PackagePath="fable\" />
  </ItemGroup>
```

That's exactly what other Fable libraries do as well, e. g. [Fable.React](https://github.com/fable-compiler/fable-react/blob/62c0c88830c72e11bab32ad9686fb8aa9ef1289a/src/Fable.React/Fable.React.fsproj#L14-L16).

**Comment by danyx23** [comment] 2018-07-04 10:07
@cmeeren sure, let me explain in more detail. It seems that one step that the Fable compiler (not the normal f# compiler) does, is that it checks the assembly for it's dependencies and checks if these can be handled by Fable. A few assemblies seem to be whitelisted (e.g. FSharp.Core), but some dependencies that are pulled in by the NET45 and NETStandard 1.6 targets fall outside this list and thus Fable refuses to compile even though all the actual code used could be transpiled. I would argue that this should be improved on the Fable side (taking the compile target of the consuming client into account when doing this process). but this seems to be where we are.

@inosik I have a branch that I used to try this and would already have sent a PR but with the current dependendy setup where this library targets also .NET Standard 1.6 and NET45 I was not able to get fable to actually build a project consuming this library after the ItemGroup changes (Fable fails with "Cannot find replacement for ..."). Have you tried building a Fable client that references this library with these changes? If you like you can use our test fork with a paket config like this:
```
git https://github.com/DouglasConnect/Cvdm.ErrorHandling.git fable-deploy-test Packages: /nuget/
nuget Cvdm.ErrorHandling 0.5.1
```
Version 0.5.1 of the nuget package in this github fork adds the ItemGroup so that the nuget package contains the F# code, Version 0.5.2 removes the netstandard1.6 and NET45 targest and only works with netstandard 2.0. In my experiments I could only compile a fable client using 0.5.2 of the library

**Comment by danyx23** [comment] 2018-07-04 10:09
Targeting NetStandard2.0 exclusively would mean that only applications targeting either the full dotnet framekwork >= 4.6.1 or Dotnet Core >= 2.0 could use this library (or libraries targeting NetStandard >= 2.0 or one of the above implementation versions)

**Comment by inosik** [comment] 2018-07-04 10:28
With your version of the package (0.5.1, with `net45/` and `netstandard1.6/`) I'm getting this error:

```
fable: Compiled src\Playground.fs
G:/playground/src/Playground.fs(5,26): (5,32) error FSHARP: The value or constructor 'result' is not defined. Maybe you want one of the following:
   Result
   ResultModule
```

The `Playground.fs` file looks like this:

``` fsharp
module Playground
// open Cvdm.ErrorHandling
let y : Result<_, unit> = result {
    return true
}
```

If I uncomment the `open` statement, the code compiles.

The problem is that the `AutoOpen` attribute bahaves differently if it is used in a file in the same project. And that's what Fable does, it puts all source files of the libraries into one project. You can try that by including the `ResultBuilder.fs` file in your project.

**Comment by danyx23** [comment] 2018-07-04 11:09
@inosik interesting, this alone does not help in my tests. I have pushed my code here (https://github.com/DouglasConnect/Cvdm.ErrorHandling.Fable.Test), the initial commit uses 0.5.1 with an *explicit open statement* like yours and does not build (yarn && yarn build), the second commit (0.5.2, NetStandard2.0 only) builds without problems.

**Comment by inosik** [comment] 2018-07-04 11:25
> The problem is that the AutoOpen attribute bahaves differently if it is used in a file in the same project. And that's what Fable does, it puts all source files of the libraries into one project. You can try that by including the ResultBuilder.fs file in your project.

Scratch that, I just discovered that this project has this in `AssemblyInfo.fs`:

``` fsharp
[<assembly:AutoOpen("Cvdm.ErrorHandling")>]
```

@danyx23 Can you verify that the `~/.nuget/packages/Cvdm.ErrorHandling/0.5.1/fable/` directory exists? You might have a problem with this specific version because it already exists on NuGet.

**Comment by danyx23** [comment] 2018-07-04 15:38
@inosik you are indeed right, thanks for persisting! I thought that paket would prioritise a git source the way I had configured it but it turned out that it used the cached version. So indeed the dependencies are NOT a problem and simply including the *.fs files and *.fsproj files works and makes this library useable with fable. Thanks everyone for your patience and help!

I'll send the PR now that adds the config to make this package fable compatible

**Comment by cmeeren** [comment] 2018-07-04 21:14
Closed by #8

**Closed as completed by cmeeren** 2018-07-04 21:14 UTC

**Comment by cmeeren** [comment] 2018-07-04 22:59
@inosik (or @danyx23) I just pushed v1.0.0. Should be available on NuGet once it's indexed. Could either of you give it a spin in Fable and verify that it works?

**Comment by inosik** [comment] 2018-07-05 05:43
I can confirm that 1.0.0 works 👍

**Comment by cmeeren** [comment] 2018-07-05 08:19
Great, thanks! 🎉
